export enum TicketServiceType {
  Antennas = 'Antennas',
  AntiVirus = 'Anti-Virus',
  BackupAggregationTargets = 'Backup Aggregation Targets',
  CustomDevices = 'Custom Devices',
  DedicatedServers = 'Dedicated Servers',
  Dns = 'DNS',
  Firewalls = 'Firewalls',
  Hids = 'HIDS',
  InternetPorts = 'Internet Ports',
  Licenses = 'Licenses',
  MicrosoftManagementServices = 'Microsoft Management Services',
  MicrosoftSubscriptions = 'Microsoft Subscriptions',
  Racks = 'Racks',
  Reservations = 'Reservations',
  Rooms = 'Rooms',
  ServerBackup = 'Server Backup',
  Servers = 'Servers',
  SoftwareSubscriptions = 'Software Subscriptions',
  StandarsSquareMetres = 'Standard Square Metres',
  VdcStorage = 'VDC Storage',
  Vdcs = 'VDCs',
  VmBackup = 'VM Backup'
}
