import { ServerMedia } from './server-media';
import { ServerFileSystem } from './server-file-system';
import { ServerStorageDevice } from './server-storage-device';
import { ServerInterface } from './server-interface';
import { ServerEnvironmentSummary } from './server-environment-summary';
import { ServerPowerState } from '../enumerations/server-power-state.enum';
import { ServerServiceType } from '../enumerations/server-service-type.enum';

export class Server {
  public id: any;
  public serviceId: string;
  public managementName: string;
  public managementIpAddress: string;
  public hardwareType: string;
  public hardwareVendor: string;
  public deviceType: string;
  public cpuCount: number;
  public coreCount: number;
  public memoryMB: number;
  public osType: string;
  public hostName: string;
  public osVendor: string;
  public osRelease: string;
  public osVersion: string;
  public communityString: string;
  public serialNumber: string;
  public updatedOn: Date;
  public threadCount: number;
  public ipAddress: string;
  public vpxId: number;
  public vmwareParentVpxId: number;
  public vmWareDescription: string;
  public os: string;
  public diskCount: number;
  public networkInterfaceCount: number;
  public powerState: ServerPowerState;
  public isTemplate: boolean;
  public companyId: string;
  public macBillId: string;
  public completedOn: Date;
  public installedOn: Date;
  public serviceDescription: string;
  public snmpVersion: string;
  public instanceId: any;
  public environment: ServerEnvironmentSummary;
  public portalUrl: string;
  public serviceType: ServerServiceType;
  public availabilityZone: string;
  public interfaces: ServerInterface[];
  public fileSystem: ServerFileSystem[];
  public storageDevice: ServerStorageDevice[];
  public media: ServerMedia[];
}
