import { ServerMedia } from './server-media';
import { ServerFileSystem } from './server-file-system';
import { ServerInterface } from './server-interface';
import { ServerPowerState } from './server-power-state.enum';

export class Server {
  public id: any;
  public serviceId: string;
  public managementName: string;
  public managementIpAddress: string;
  public hardwareType: string;
  public hardwareVendor: string;
  public deviceType: string;
  public cpuCount: number;
  public coreCount: number;
  public memoryMb: number;
  public osType: string;
  public hostName: string;
  public osVendor: string;
  public osRelease: string;
  public osVersion: string;
  public communityString: string;
  public serialNumber: string;
  public lastUpdate: Date;
  public threadCount: number;
  public ipAddress: string;
  public vpxId: number;
  public vmwareParentVpxId: number;
  public vmWareDescription: string;
  public guestOS: string;
  public diskCount: number;
  public networkInterfaceCount: number;
  public powerState: ServerPowerState;
  public isTempalte: boolean;
  public companyId: string;
  public macBillId: string;
  public dateCompleted: Date;
  public dateInstalled: Date;
  public serviceDescription: string;
  public snmpVersion: string;
  public instanceId: any;
  public organizationName: string;
  public vdcName: string;
  public vdcAppName: string;
  public vCloudUrl: string;
  public serviceType: string;
  public storagePolicy: string;
  public interfaces: ServerInterface[];
  public fileSystem: ServerFileSystem[];
  public media: ServerMedia[];
}
