export enum CloudHealthAlertType {
  ManagementTags = 'Management Tags',
  UnattachedDisks = 'Unattached Disks',
  OldSnapshots = 'Old Snapshots',
  UnattachedIpAddresses = 'Unattached IP Addresses',
  StorageAccountSecureTransfer = 'Storage Account Secure Transfer',
  StorageBlobContainerPublicAccess = 'Storage Blob Container Public Access',
  SQLServerAuditingDisabled = 'SQL Server Auditing Disabled',
  StorageContainerActivityLogsPubliclyAccessible = 'Storage Container Activity Logs Publicly Accessible',
  SecurityContactEmailNotConfigured = 'Security Contact Email Not Configured',
  AzureDefenderDisabledStorageAccount = 'Azure Defender Disabled for Storage Account',
  WindowsDefenderATPIntegrationNotSelected = ' Windows Defender ATP Integration Not Selected',
  AzureDefenderDisabledSQLServerMachine = 'Azure Defender Disabled for SQL Server on Machine',
  AzureDefenderDisabledAppService = 'Azure Defender Disabled for App Service',
  AzureDefenderDisabledServer = 'Azure Defender Disabled for Server',
  AzureDefenderDisabledSQLDatabaseServer = 'Azure Defender Disabled for SQL Database Server',
  AzureDefenderDisabledKeyVault = 'Azure Defender Disabled for Key Vault',
  AzureDefenderDisabledKubernetesService = 'Azure Defender Disabled for Kubernetes Service',
  AzureDefenderDisabledContainerRegistry = 'Azure Defender Disabled for Container Registry',
  SQLServerThreatDetectionDisabled = 'SQL Server Threat Detection Disabled',
  SQLServerVulnerabilityAssessmentNoStorageAccountConfigured = 'SQL Server Vulnerability Assessment No Storage Account Configured',
  SQLServerVulnerabilityAssessmentPeriodicScansDisabled = 'SQL Server Vulnerability Assessment Periodic Scans Disabled',
  SQLServerVulnerabilityAssessmentEmailNotConfigured = 'SQL Server Vulnerability Assessment Email Not Configured',
  SQLServerVulnerabilityAssessmentEmailSubscriptionAdminsNotConfigured = 'SQL Server Vulnerability Assessment Email Subscription Admins Not Configured',
  LoggingDisabledforKeyVault = 'Logging Disabled for Key Vault',
}