export enum RouteKey {
  Dashboard = 1,

  LaunchPad,
  LaunchPadSearch,
  LaunchPadWorkflowLaunch,

  LaunchPadAzureDeployments,
  LaunchPadAzureDeploymentCreate,
  LaunchPadAzureDeploymentDetails,
  LaunchPadAzureDeploymentDetailsOverview,
  LaunchPadAzureDeploymentDetailsHistory,

  LaunchPadNetworkDbSites,
  LaunchPadNetworkDbPods,
  LaunchPadNetworkDbVlans,
  LaunchPadNetworkDbVlanDetails,
  LaunchPadNetworkDbVlanDetailsOverview,
  LaunchPadNetworkDbVlanDetailsEvents,
  LaunchPadNetworkDbVnis,
  LaunchPadNetworkDbUseCases,
  LaunchPadNetworkDbMulticastIps,
  LaunchPadNetworkDbNetworks,
  LaunchPadNetworkDbNetworkCreate,
  LaunchPadNetworkDbNetworkDetails,
  LaunchPadNetworkDbNetworkDetailsOverview,
  LaunchPadNetworkDbNetworkDetailsEvents,
  LaunchPadNetworkDbNetworkDetailsEdit,
  LaunchPadNetworkDbNetworkDetailsVlans,

  LaunchPadVCenterBaselines,
  LaunchPadVCenterRemediateEsxiHosts,

  LaunchPadCrispOrders,
  LaunchPadCrispOrderDetails,
  LaunchPadCrispOrderDetailsElements,

  LaunchPadDashboardProjects,
  LaunchPadDashboardProjectDetails,
  LaunchPadDashboardProjectDetailsTasks,

  ReportOverview,
  ReportInsights,

  Azure,
  AzureSoftwareSubscriptions,
  AzureSubscriptions,
  AzureManagementServices,
  AzureManagementServicesDetails,
  AzureManagementServicesDetailsOverview,
  AzureManagementServicesDetailsChildren,
  AzureResources,
  AzureReservations,
  AzureNonStandardBundles,

  Console,
  Maintenance,
  SystemMessagePage,

  Servers,
  ServerDetails,
  ServerDetailsManagement,
  ServerDetailsServices,
  ServerDetailsStorage,
  ServerDetailsSnapshots,
  ServerDetailsNics,
  ServerCreate,

  SystemMessages,
  SystemMessageCreate,
  SystemMessageEdit,

  Resources,
  ResourceDetails,
  ResourceDetailsOverview,
  ResourceDetailsStorage,

  Media,
  Medium,
  MediumOverview,
  MediumServers,
  MediaUpload,

  Firewalls,
  FirewallDetails,
  FirewallDetailsOverview,
  FirewallDetailsPolicies,

  BackupAggregationTargets,
  BackupAggregationTargetsDetails,
  BackupAggregationTargetsDetailsManagement,
  BackupAggregationTargetsDetailsLinkedServices,

  SaasBackups,
  SaasBackupDetails,
  SaasBackupDetailsOverview,
  SaasBackupDetailsManagement,

  Tickets,
  TicketDetails,
  TicketCreate,

  Notifications,
  Activities,
  Activity,
  Notices,
  Notice,
  NoticeOverview,
  NoticeAssociatedService,

  PlannedWorkListing,
  PlannedWorkDetails,
  PlannedWorkDetailsOverview,
  PlannedWorkAffectedServices,

  ProductDetails, // Deprecated

  Catalog,
  CatalogProductsPlatform,
  CatalogProduct,
  CatalogSolution,
  CatalogSolutions,

  DnsZoneListing,
  DnsZoneDetails,
  DnsZoneOverview,
  DnsZoneRecords,
  DnsServiceDetails,
  DnsServiceOverview,

  Orders,
  OrdersHistory,
  OrderDetails,
  OrdersDashboard,
  OrderServerManagedScale,
  OrderVdcScale,
  OrderVdcStorageExpand,
  OrderVdcStorageCreate,
  OrderServiceInviewRaise,
  OrderServiceCustomChange,
  OrderHostedDnsChange,
  OrderColocationStaffEscort,
  OrderColocationDeviceRestart,
  OrderAddAntiVirus,
  OrderAddHids,
  OrderAddServerBackup,
  OrderAddVmBackup,
  OrderAddBat,
  OrderRestoreBackupRequest,
  OrderMsLicenseCountChange,
  OrderMsRequestChange,
  OrderRemoteHands,
  OrderServerRequestPatch,
  OrderAddSimpleFirewallChange,
  OrderModifySimpleFirewallChange,
  OrderRemoveSimpleFirewallChange,
  OrderComplexFirewallChange,
  OrderChangeInternetPortPlan,
  OrderAzureProfessionalServiceRequest,
  OrderPrivateCloudChangeLaunchExtenderSpeed,
  OrderChangeAzureExtendSpeed,
  OrderChangeApplicationRecoveryQuota,

  Internet,
  InternetDetails,
  InternetDetailsManagement,

  OtherTools,
  Licenses,

  Billing,
  BillingSummary,
  BillingService,

  Avd,
  AvdDailyUserService,
  AvdDailyUserAverage,
  AvdServiceCost,
  AvdDailyConnection,

  PrivateCloudDashboard,
  PrivateCloudDashboardOverview,

  HybridCloud,
  Extenders,
  ApplicationRecovery,
  
  KnowledgeBaseInterstitial,

  HttpErrorPage
}
