name: Lab (Build and Deploy)

on:
  push:
    branches: [ "release" ]
  workflow_dispatch: 

jobs:
  init:
    name: init vars
    runs-on: ubuntu-latest
    environment: staging

    outputs:
      IMAGE_VERSION: ${{ steps.vars.outputs.image_version}}
      
    steps:
    - uses: actions/checkout@v3
    
    - name: vars
      id: vars
      run: |
        build_target=${GITHUB_REF#refs/*/}
        version=${build_target////-}
        short_sha=$(git rev-parse --short HEAD)
        now=$(date +'%Y%m%dT%H%M%S')
        ver=${version}-${short_sha}-${now}
        
        echo $ver
        echo "image_version=${ver}" >> $GITHUB_OUTPUT

  call-build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    with:
      environment: staging
      is_run_test: false
      is_upload_artifacts: true
    
  call-publish:
    uses: ./.github/workflows/publish.yml
    needs: [init, call-build-and-test]
    
    with:
      environment: staging
      image_version: ${{ needs.init.outputs.IMAGE_VERSION }}
      is_image_latest: true
    secrets: inherit

  
  call-deploy:
    uses: ./.github/workflows/deploy.yml
    needs: [init, call-publish]
    with:
      environment: staging
      image_version: ${{ needs.init.outputs.IMAGE_VERSION }}
    secrets: inherit
    